title: Lerntagebuch Modul "BAIN"
author: Tanja Vogel
email: tanja.vogel@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch für das Modul Bibliotheks- und Archivinformatik FS2020

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
